version: '2.2'

services:
  rabbitmq:
      image: 'rabbitmq:3.9.13-management-alpine'
      container_name: "rabbitmq"
      restart: always
      networks:
      - elastic
      environment:
        - "RABBITMQ_DEFAULT_USER=username"
        - "RABBITMQ_DEFAULT_PASS=password"
      ports:
        - '15672:15672'
        - '5672:5672'
      expose:
        - '15672:15672'
        - '5672:5672'
  postgres:
    image: postgres:13.6-alpine
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: budget
      POSTGRES_ROOT_PASSWORD: dbpass
    ports:
      - 5432:5432
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  esdata:
    driver: local
networks:
  elastic:
    driver: bridge